kind: PersistentVolume
apiVersion: v1
metadata:
  name: halyard-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/halyard"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: halyard-home-spinnaker-spinnaker-halyard-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
