## JIRA
# image: seibertmedia/atlassian-jira-software:7.3.6_0.1.0
image: ealebed/jira:7.5.0
imagePullPolicy: IfNotPresent

# serviceType: LoadBalancer
serviceType: NodePort
ingressDomain: jira.example.com

maxMemoryJVM: 1G
supportArgs:

resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1

persistence:
  enabled: false
  size: 20Gi
  accessMode: ReadWriteOnce
  storageClass: standard

postgresql:
  imageTag: "9.5"
  cpu: 100m
  memory: 256Mi

  postgresUser: jira
  postgresPassword: jira
  postgresDatabase: jira

  persistence:
    size: 5Gi
    storageClass: standard
    enabled: false
